from .classify import NLPClassifyModel
from .conversational import NLPConversationalModel
from .fill import NLPFillModel
from .generate import NLPGenerateModel
from .qna import NLPQnaModel
from .recognise import NLPRecogniseModel
from .similarity import NLPSimilarityModel
from .summarise import NLPSummariseModel
from .table import NLPTableModel
from .translate import NLPTranslateModel
from .zero_shot_classify import NLPZeroShotClassifyModel
